In [19]:
from pathlib import Path
import numpy as np 
import pandas as pd
import os

In [27]:
direc = Path(r'C:\Users\Krul\Documents\GitHub\cell-painting-dashboard\data\processed')
# direc
filepaths = list(direc.glob(r'**/*.tiff'))
# filepaths
FileNames = list(map(lambda x: os.path.split(x)[1],filepaths))
filepaths = pd.Series(filepaths, name='FilePaths').astype(str)
Labels = pd.Series(FileNames, name='FileNames').astype(str)
img_df = pd.merge(filepaths, Labels, right_index = True, left_index = True)
img_df

,FilePaths,FileNames
0,C:\Users\Krul\Documents\GitHub\cell-painting-d...,r01c01f01p01-ch1sk1fk1fl1.tiff
1,C:\Users\Krul\Documents\GitHub\cell-painting-d...,r01c01f01p01-ch2sk1fk1fl1.tiff
2,C:\Users\Krul\Documents\GitHub\cell-painting-d...,r01c01f01p01-ch3sk1fk1fl1.tiff
3,C:\Users\Krul\Documents\GitHub\cell-painting-d...,r01c01f01p01-ch4sk1fk1fl1.tiff
4,C:\Users\Krul\Documents\GitHub\cell-painting-d...,r01c01f02p01-ch1sk1fk1fl1.tiff
...,...,...
3451,C:\Users\Krul\Documents\GitHub\cell-painting-d...,r16c24f08p01-ch4sk1fk1fl1.tiff
3452,C:\Users\Krul\Documents\GitHub\cell-painting-d...,r16c24f09p01-ch1sk1fk1fl1.tiff
3453,C:\Users\Krul\Documents\GitHub\cell-painting-d...,r16c24f09p01-ch2sk1fk1fl1.tiff
3454,C:\Users\Krul\Documents\GitHub\cell-painting-d...,r16c24f09p01-ch3sk1fk1fl1.tiff
3455,C:\Users\Krul\Documents\GitHub\cell-painting-d...,r16c24f09p01-ch4sk1fk1fl1.tiff

In [42]:
img_df = pd.merge(filepaths, Labels, right_index = True, left_index = True)
img_df['Row'] = img_df['FileNames'].apply(lambda x: x[1:3]).apply(lambda x: chr(int(x)+64))
img_df['Column'] = img_df['FileNames'].apply(lambda x: x[4:6])
img_df['F'] = img_df['FileNames'].apply(lambda x: x[7:9]) 
img_df['Well'] = img_df['Row'] + img_df['Column']
for aa in ['ch1', 'ch2', 'ch3', 'ch4']:
    img_df['FileNames'] = img_df['FileNames'].apply(lambda x: x.replace(aa,''))

img_df = img_df.drop('FilePaths', axis=1)
img_df

                        FileNames Row Column   F Well
0     r01c01f01p01-sk1fk1fl1.tiff   A     01  01  A01
1     r01c01f01p01-sk1fk1fl1.tiff   A     01  01  A01
2     r01c01f01p01-sk1fk1fl1.tiff   A     01  01  A01
3     r01c01f01p01-sk1fk1fl1.tiff   A     01  01  A01
4     r01c01f02p01-sk1fk1fl1.tiff   A     01  02  A01
...                           ...  ..    ...  ..  ...
3451  r16c24f08p01-sk1fk1fl1.tiff   P     24  08  P24
3452  r16c24f09p01-sk1fk1fl1.tiff   P     24  09  P24
3453  r16c24f09p01-sk1fk1fl1.tiff   P     24  09  P24
3454  r16c24f09p01-sk1fk1fl1.tiff   P     24  09  P24
3455  r16c24f09p01-sk1fk1fl1.tiff   P     24  09  P24

[3456 rows x 5 columns]

In [43]:
img_df = img_df.drop_duplicates().reset_index(drop=True)
img_df

                       FileNames Row Column   F Well
0    r01c01f01p01-sk1fk1fl1.tiff   A     01  01  A01
1    r01c01f02p01-sk1fk1fl1.tiff   A     01  02  A01
2    r01c01f03p01-sk1fk1fl1.tiff   A     01  03  A01
3    r01c01f04p01-sk1fk1fl1.tiff   A     01  04  A01
4    r01c01f05p01-sk1fk1fl1.tiff   A     01  05  A01
..                           ...  ..    ...  ..  ...
859  r16c24f05p01-sk1fk1fl1.tiff   P     24  05  P24
860  r16c24f06p01-sk1fk1fl1.tiff   P     24  06  P24
861  r16c24f07p01-sk1fk1fl1.tiff   P     24  07  P24
862  r16c24f08p01-sk1fk1fl1.tiff   P     24  08  P24
863  r16c24f09p01-sk1fk1fl1.tiff   P     24  09  P24

[864 rows x 5 columns]

In [44]:
well_df = pd.read_csv('E:\data\Cell-Painting-HepG2-Plate-Layouts.csv', usecols=[0,1,2])
well_df

    Well            Compound  Concentration [uM]
0    A01  Berberine Chloride           50.000000
1    A02  Berberine Chloride           25.000000
2    A03  Berberine Chloride           12.500000
3    A04  Berberine Chloride            6.250000
4    A05  Berberine Chloride            3.166667
..   ...                 ...                 ...
379  P20         Tetrandrine            0.166667
380  P21         Tetrandrine            0.083333
381  P22         Tetrandrine            0.041667
382  P23                DMSO                 NaN
383  P24                DMSO                 NaN

[384 rows x 3 columns]

In [46]:
img_df.merge(well_df)

,FileNames,Row,Column,F,Well,Compound,Concentration [uM]
0,r01c01f01p01-sk1fk1fl1.tiff,A,01,01,A01,Berberine Chloride,50.0
1,r01c01f02p01-sk1fk1fl1.tiff,A,01,02,A01,Berberine Chloride,50.0
2,r01c01f03p01-sk1fk1fl1.tiff,A,01,03,A01,Berberine Chloride,50.0
3,r01c01f04p01-sk1fk1fl1.tiff,A,01,04,A01,Berberine Chloride,50.0
4,r01c01f05p01-sk1fk1fl1.tiff,A,01,05,A01,Berberine Chloride,50.0
...,...,...,...,...,...,...,...
859,r16c24f05p01-sk1fk1fl1.tiff,P,24,05,P24,DMSO,NaN
860,r16c24f06p01-sk1fk1fl1.tiff,P,24,06,P24,DMSO,NaN
861,r16c24f07p01-sk1fk1fl1.tiff,P,24,07,P24,DMSO,NaN
862,r16c24f08p01-sk1fk1fl1.tiff,P,24,08,P24,DMSO,NaN
863,r16c24f09p01-sk1fk1fl1.tiff,P,24,09,P24,DMSO,NaN